config: local_tmp="/scratch"
jobs: 24
local-cores: 1
rerun-incomplete: true
keep-going: true
use-conda: true
conda-frontend: mamba
printshellcmds: true
reason: true
# restart-times: 3
# max-jobs-per-second: 1
# max-status-checks-per-second: 10
# local-cores: 1
# latency-wait: 60
